<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sonibot_base">

<xacro:include filename="$(find sonibot_description)/urdf/common_properties.xacro"/>
<xacro:include filename="$(find sonibot_description)/urdf/sonibot_base.gazebo.xacro"/>

<!--###################### ROBOT BASE ##################################-->
  <!-- Dummy link -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.02" rpy="0.0 0.0 0.0"/>
    </joint>

  <!-- Base link -->
    <link name="base_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="4.0"/>
            <xacro:box_inertia m="4.0" x="0.3" y="0.2" z="0.02"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.3 0.2 0.02"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.3 0.2 0.02"/>
            </geometry>
        </collision>
    </link>

  <!-- Left wheel -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0.075 ${0.1+0.01} 0" rpy="${-M_PI_2} 0 0"/>
    </joint>

    <link name="left_wheel_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.5"/>
            <xacro:cylinder_inertia m="0.5" r="0.04" l="0.02"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.04" length="0.02"/>
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.04" length="0.02"/>
            </geometry>
        </collision>
    </link>

  <!-- Right wheel -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0.075 ${-0.1-0.01} 0" rpy="${-M_PI_2} 0 0"/>
    </joint>

    <link name="right_wheel_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.5"/>
            <xacro:cylinder_inertia m="0.5" r="0.04" l="0.02"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.04" length="0.02"/>
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.04" length="0.02"/>
            </geometry>
        </collision>
    </link>

  <!-- Left caster -->
    <joint name="left_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_caster_link"/>
        <origin xyz="-0.075 0.1 -0.025" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="left_caster_link">
        <inertial>
            <mass value="0.5"/>
            <inertia  ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001" />
        </inertial>
        <!-- <visual>
            <geometry>
                <box size="0.03 0.02 0.03"/>
            </geometry>
        </visual> -->
        <collision>
            <origin xyz="0.0 0.0 0.001"/>
            <geometry>
                <box size="0.03 0.02 0.03"/>
            </geometry>
        </collision>
    </link>

  <!-- Right caster -->
    <joint name="right_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_caster_link"/>
        <origin xyz="-0.075 -0.1 -0.025" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="right_caster_link">
        <inertial>
            <mass value="0.5"/>
            <inertia  ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001" />
        </inertial>
        <!-- <visual>
            <geometry>
                <box size="0.03 0.02 0.03"/>
            </geometry>
        </visual> -->
        <collision>
            <origin xyz="0.0 0.0 0.001"/>
            <geometry>
                <box size="0.03 0.02 0.03"/>
            </geometry>
        </collision>
    </link>


<!--###################### SENSORS #####################################-->
  <!-- Imu -->
    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0.0 0.0 0.01" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="imu_link"/>
  
  <!-- Lidar -->
    <joint name="scan_joint" type="fixed">
        <parent link="base_link"/>
        <child link="scan_link"/>
        <origin xyz="0.1 0.0 0.1" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="scan_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia  ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001" />
        </inertial>
        <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <mesh filename="package://sonibot_description/meshes/lds.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="dark"/>
        </visual>
        <collision>
        <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
        <geometry>
            <cylinder length="0.0315" radius="0.055"/>
        </geometry>
        </collision>
    </link> 

  <!-- RGB Camera -->
    <!--Camera link -->
    <joint name="camera_joint" type="fixed">
        <origin xyz="0.15 -0.06 0.01" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>

    <link name="camera_link">
        <visual>
        <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
        <geometry>
        <mesh filename="package://sonibot_description/meshes/r200.dae" />
        </geometry>
        </visual>
        <collision>
        <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
        <geometry>
            <box size="0.012 0.132 0.020"/>
        </geometry>
        </collision>
    </link>
    <!-- Camera parameters -->
    <xacro:property name="r200_cam_rgb_px" value="0.005"/>
    <xacro:property name="r200_cam_rgb_py" value="0.018"/>
    <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
    <xacro:property name="r200_cam_depth_offset" value="0.01"/>
    <!-- Other links -->
    <joint name="camera_rgb_joint" type="fixed">
        <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
        <parent link="camera_link"/>
        <child link="camera_rgb_frame"/>
    </joint>
    <link name="camera_rgb_frame"/>

    <joint name="camera_rgb_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="camera_rgb_frame"/>
        <child link="camera_rgb_optical_frame"/>
    </joint>
    <link name="camera_rgb_optical_frame"/>

    <joint name="camera_depth_joint" type="fixed">
        <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
        <parent link="camera_link"/>
        <child link="camera_depth_frame"/>
    </joint>
    <link name="camera_depth_frame"/>

    <joint name="camera_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="camera_depth_frame"/>
        <child link="camera_depth_optical_frame"/>
    </joint>
    <link name="camera_depth_optical_frame"/>

<!--###################### TRANSMISSIONS ###############################-->
    <!--If "libgazebo_ros_diff_drive.so" plugin is used to control wheels, you can ignore the below code-->
    <!-- This code is used for ros_control controllers -->

    <!-- left wheel -->
        <transmission name="left_wheel_trans" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="left_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="left_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>
    <!-- right wheel -->
        <transmission name="right_wheel_trans" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="right_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="right_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>

</robot>